language: python
python: 2.7
sudo: false
services:
    - elasticsearch

install:
    - pip install -r requirements/test.txt
    - git fetch origin master:refs/remotes/origin/master # https://github.com/edx/diff-cover#troubleshooting
    - pip install coveralls

script:
    - make validate

after_success:
    - coveralls
